[project]
name = "learn_quarto-revealjs"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
ipykernel = "6.25.2.*"
nbformat = "5.9.2.*"
nbclient = "0.8.0.*"
pandas = "2.1.1.*"
matplotlib = "3.8.0.*"
jupyter = "1.0.0.*"
